"""empty message

Revision ID: 0873b959780e
Revises: cb8ef1bc2bd4
Create Date: 2020-03-30 17:49:00.180470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0873b959780e'
down_revision = 'cb8ef1bc2bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indice', sa.Column('areacode', sa.String(length=20), nullable=True))
    op.add_column('indice', sa.Column('launchdate', sa.Date(), nullable=True))
    op.add_column('indice', sa.Column('pb_avgval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_chanceval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_latestval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_latestvalpos', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_maxpositiveval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_maxval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_maxvaldate', sa.Date(), nullable=True))
    op.add_column('indice', sa.Column('pb_medianval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_minval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_minvaldate', sa.Date(), nullable=True))
    op.add_column('indice', sa.Column('pb_riskval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_avgval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_chanceval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_latestval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_latestvalpos', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_maxpositiveval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_maxval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_maxvaldate', sa.Date(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_medianval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_minval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_minvaldate', sa.Date(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_riskval', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('stockcode', sa.String(length=20), nullable=True))
    op.add_column('indice', sa.Column('stockid', sa.BigInteger(), nullable=True))
    op.drop_column('indice', 'pb_latestVal')
    op.drop_column('indice', 'stockId')
    op.drop_column('indice', 'pb_latestValPos')
    op.drop_column('indice', 'pe_ttm_riskVal')
    op.drop_column('indice', 'stockCode')
    op.drop_column('indice', 'pe_ttm_maxVal')
    op.drop_column('indice', 'pe_ttm_medianVal')
    op.drop_column('indice', 'pb_maxVal')
    op.drop_column('indice', 'pe_ttm_latestValPos')
    op.drop_column('indice', 'pb_riskVal')
    op.drop_column('indice', 'pe_ttm_maxPositiveVal')
    op.drop_column('indice', 'pe_ttm_minValDate')
    op.drop_column('indice', 'pe_ttm_maxValDate')
    op.drop_column('indice', 'pe_ttm_avgVal')
    op.drop_column('indice', 'pb_minVal')
    op.drop_column('indice', 'areaCode')
    op.drop_column('indice', 'pb_maxPositiveVal')
    op.drop_column('indice', 'pb_chanceVal')
    op.drop_column('indice', 'pe_ttm_chanceVal')
    op.drop_column('indice', 'pb_medianVal')
    op.drop_column('indice', 'pb_avgVal')
    op.drop_column('indice', 'launchDate')
    op.drop_column('indice', 'pe_ttm_minVal')
    op.drop_column('indice', 'pb_maxValDate')
    op.drop_column('indice', 'pb_minValDate')
    op.drop_column('indice', 'pe_ttm_latestVal')
    op.add_column('pe_pb', sa.Column('stockid', sa.BigInteger(), nullable=True))
    op.drop_column('pe_pb', 'stockId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pe_pb', sa.Column('stockId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('pe_pb', 'stockid')
    op.add_column('indice', sa.Column('pe_ttm_latestVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pb_minValDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pb_maxValDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_minVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('launchDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pb_avgVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pb_medianVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_chanceVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pb_chanceVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pb_maxPositiveVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('areaCode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pb_minVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_avgVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_maxValDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_minValDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_maxPositiveVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pb_riskVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_latestValPos', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pb_maxVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_medianVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_maxVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('stockCode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_riskVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pb_latestValPos', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('stockId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pb_latestVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('indice', 'stockid')
    op.drop_column('indice', 'stockcode')
    op.drop_column('indice', 'pe_ttm_riskval')
    op.drop_column('indice', 'pe_ttm_minvaldate')
    op.drop_column('indice', 'pe_ttm_minval')
    op.drop_column('indice', 'pe_ttm_medianval')
    op.drop_column('indice', 'pe_ttm_maxvaldate')
    op.drop_column('indice', 'pe_ttm_maxval')
    op.drop_column('indice', 'pe_ttm_maxpositiveval')
    op.drop_column('indice', 'pe_ttm_latestvalpos')
    op.drop_column('indice', 'pe_ttm_latestval')
    op.drop_column('indice', 'pe_ttm_chanceval')
    op.drop_column('indice', 'pe_ttm_avgval')
    op.drop_column('indice', 'pb_riskval')
    op.drop_column('indice', 'pb_minvaldate')
    op.drop_column('indice', 'pb_minval')
    op.drop_column('indice', 'pb_medianval')
    op.drop_column('indice', 'pb_maxvaldate')
    op.drop_column('indice', 'pb_maxval')
    op.drop_column('indice', 'pb_maxpositiveval')
    op.drop_column('indice', 'pb_latestvalpos')
    op.drop_column('indice', 'pb_latestval')
    op.drop_column('indice', 'pb_chanceval')
    op.drop_column('indice', 'pb_avgval')
    op.drop_column('indice', 'launchdate')
    op.drop_column('indice', 'areacode')
    # ### end Alembic commands ###
