"""empty message

Revision ID: 125952b74684
Revises: dfa5bb8538c3
Create Date: 2020-03-29 12:01:51.357841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125952b74684'
down_revision = 'dfa5bb8538c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pe_pb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('stockId', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('cp', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('pb_avgVal', sa.Float(), nullable=True),
    sa.Column('pb_chanceVal', sa.Float(), nullable=True),
    sa.Column('pb_latestValPos', sa.Float(), nullable=True),
    sa.Column('pb_maxVal', sa.Float(), nullable=True),
    sa.Column('pb_medianVal', sa.Float(), nullable=True),
    sa.Column('pb_minVal', sa.Float(), nullable=True),
    sa.Column('pb_riskVal', sa.Float(), nullable=True),
    sa.Column('pb_latestVal', sa.Float(), nullable=True),
    sa.Column('pe_ttm', sa.Float(), nullable=True),
    sa.Column('pe_avgVal', sa.Float(), nullable=True),
    sa.Column('pe_chanceVal', sa.Float(), nullable=True),
    sa.Column('pe_latestValPos', sa.Float(), nullable=True),
    sa.Column('pe_maxVal', sa.Float(), nullable=True),
    sa.Column('pe_medianVal', sa.Float(), nullable=True),
    sa.Column('pe_minVal', sa.Float(), nullable=True),
    sa.Column('pe_riskVal', sa.Float(), nullable=True),
    sa.Column('pe_latestVal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pe_pb')
    # ### end Alembic commands ###
