"""empty message

Revision ID: 1bf2715c1e0f
Revises: af4abb98d03e
Create Date: 2020-03-29 22:30:25.609992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bf2715c1e0f'
down_revision = 'af4abb98d03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indice', sa.Column('pe_ttm_avgVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_chanceVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_latestVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_latestValPos', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_maxVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_medianVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_minVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_riskVal', sa.Float(), nullable=True))
    op.drop_column('indice', 'pe_riskVal')
    op.drop_column('indice', 'pe_latestValPos')
    op.drop_column('indice', 'pe_avgVal')
    op.drop_column('indice', 'pe_maxVal')
    op.drop_column('indice', 'pe_medianVal')
    op.drop_column('indice', 'pe_chanceVal')
    op.drop_column('indice', 'pe_minVal')
    op.drop_column('indice', 'pe_latestVal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indice', sa.Column('pe_latestVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_minVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_chanceVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_medianVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_maxVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_avgVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_latestValPos', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('indice', sa.Column('pe_riskVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('indice', 'pe_ttm_riskVal')
    op.drop_column('indice', 'pe_ttm_minVal')
    op.drop_column('indice', 'pe_ttm_medianVal')
    op.drop_column('indice', 'pe_ttm_maxVal')
    op.drop_column('indice', 'pe_ttm_latestValPos')
    op.drop_column('indice', 'pe_ttm_latestVal')
    op.drop_column('indice', 'pe_ttm_chanceVal')
    op.drop_column('indice', 'pe_ttm_avgVal')
    # ### end Alembic commands ###
