"""empty message

Revision ID: 58a6d03de721
Revises: 0873b959780e
Create Date: 2020-03-30 18:46:49.645155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a6d03de721'
down_revision = '0873b959780e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indice', sa.Column('stocktype', sa.String(length=20), nullable=True))
    op.drop_column('indice', 'stockType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indice', sa.Column('stockType', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('indice', 'stocktype')
    # ### end Alembic commands ###
