"""empty message

Revision ID: 7f398d5cd7fa
Revises: 8bc3e2ae423a
Create Date: 2020-03-26 17:47:27.450960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f398d5cd7fa'
down_revision = '8bc3e2ae423a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('subscription', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'date_modified')
    op.drop_column('subscription', 'date_created')
    # ### end Alembic commands ###
