"""empty message

Revision ID: 81510d4ba452
Revises: 7f398d5cd7fa
Create Date: 2020-03-27 21:42:34.179584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81510d4ba452'
down_revision = '7f398d5cd7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pe_ttm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('twentyp', sa.Float(), nullable=True),
    sa.Column('median', sa.Float(), nullable=True),
    sa.Column('eightyp', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pe_ttm')
    # ### end Alembic commands ###
