"""change sent_flag to last_send date

Revision ID: 8bc3e2ae423a
Revises: 59c49ef7307c
Create Date: 2020-03-20 14:22:42.615157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc3e2ae423a'
down_revision = '59c49ef7307c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('last_send', sa.Date(), nullable=True))
    op.drop_column('subscription', 'sent_flag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('sent_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('subscription', 'last_send')
    # ### end Alembic commands ###
