"""empty message

Revision ID: af4abb98d03e
Revises: 125952b74684
Create Date: 2020-03-29 22:21:53.540640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af4abb98d03e'
down_revision = '125952b74684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indice', sa.Column('pb_avgVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_chanceVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_latestVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_latestValPos', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_maxVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_medianVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_minVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pb_riskVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_avgVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_chanceVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_latestVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_latestValPos', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_maxVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_medianVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_minVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_riskVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm', sa.Float(), nullable=True))
    op.drop_column('pe_pb', 'pb_chanceVal')
    op.drop_column('pe_pb', 'pb_minVal')
    op.drop_column('pe_pb', 'pe_riskVal')
    op.drop_column('pe_pb', 'pb_latestVal')
    op.drop_column('pe_pb', 'pe_medianVal')
    op.drop_column('pe_pb', 'pe_latestVal')
    op.drop_column('pe_pb', 'pb_latestValPos')
    op.drop_column('pe_pb', 'pe_avgVal')
    op.drop_column('pe_pb', 'pe_maxVal')
    op.drop_column('pe_pb', 'pb_riskVal')
    op.drop_column('pe_pb', 'pb_avgVal')
    op.drop_column('pe_pb', 'pe_latestValPos')
    op.drop_column('pe_pb', 'pb_maxVal')
    op.drop_column('pe_pb', 'pe_minVal')
    op.drop_column('pe_pb', 'pe_chanceVal')
    op.drop_column('pe_pb', 'pb_medianVal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pe_pb', sa.Column('pb_medianVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pe_chanceVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pe_minVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pb_maxVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pe_latestValPos', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pb_avgVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pb_riskVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pe_maxVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pe_avgVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pb_latestValPos', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pe_latestVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pe_medianVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pb_latestVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pe_riskVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pb_minVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pe_pb', sa.Column('pb_chanceVal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('indice', 'pe_ttm')
    op.drop_column('indice', 'pe_riskVal')
    op.drop_column('indice', 'pe_minVal')
    op.drop_column('indice', 'pe_medianVal')
    op.drop_column('indice', 'pe_maxVal')
    op.drop_column('indice', 'pe_latestValPos')
    op.drop_column('indice', 'pe_latestVal')
    op.drop_column('indice', 'pe_chanceVal')
    op.drop_column('indice', 'pe_avgVal')
    op.drop_column('indice', 'pb_riskVal')
    op.drop_column('indice', 'pb_minVal')
    op.drop_column('indice', 'pb_medianVal')
    op.drop_column('indice', 'pb_maxVal')
    op.drop_column('indice', 'pb_latestValPos')
    op.drop_column('indice', 'pb_latestVal')
    op.drop_column('indice', 'pb_chanceVal')
    op.drop_column('indice', 'pb_avgVal')
    # ### end Alembic commands ###
