"""empty message

Revision ID: cb8ef1bc2bd4
Revises: bf747220ac64
Create Date: 2020-03-30 00:48:19.811373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb8ef1bc2bd4'
down_revision = 'bf747220ac64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indice', 'pe_ttm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indice', sa.Column('pe_ttm', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
