"""empty message

Revision ID: dfa5bb8538c3
Revises: 4806bfd56c26
Create Date: 2020-03-28 21:11:24.377605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa5bb8538c3'
down_revision = '4806bfd56c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('stockId', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('areaCode', sa.String(length=20), nullable=True),
    sa.Column('stockType', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('stockCode', sa.String(length=20), nullable=True),
    sa.Column('launchDate', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indice')
    # ### end Alembic commands ###
