"""empty message

Revision ID: e5282c65f831
Revises: 1bf2715c1e0f
Create Date: 2020-03-29 22:50:14.717402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5282c65f831'
down_revision = '1bf2715c1e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indice', sa.Column('pb_maxPositiveVal', sa.Float(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_maxPositiveVal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indice', 'pe_ttm_maxPositiveVal')
    op.drop_column('indice', 'pb_maxPositiveVal')
    # ### end Alembic commands ###
