"""empty message

Revision ID: f105cde7cbc9
Revises: 99f0ec5b7949
Create Date: 2020-04-08 19:52:37.626686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f105cde7cbc9'
down_revision = '99f0ec5b7949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_trend', sa.Column('count', sa.Integer(), nullable=False))
    op.drop_column('fund_trend', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_trend', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('fund_trend', 'count')
    # ### end Alembic commands ###
