"""empty message

Revision ID: f3f9ec31bc6f
Revises: e5282c65f831
Create Date: 2020-03-29 23:03:16.072356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f9ec31bc6f'
down_revision = 'e5282c65f831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indice', sa.Column('pb_maxValDate', sa.Date(), nullable=True))
    op.add_column('indice', sa.Column('pe_ttm_maxValDate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indice', 'pe_ttm_maxValDate')
    op.drop_column('indice', 'pb_maxValDate')
    # ### end Alembic commands ###
